bin_SSPOCon = ( [dataStruct.varParList_short.STAwidth] == 3) & ...
            ( [dataStruct.varParList_short.STAshift] == -10) & ...
            ( [dataStruct.varParList_short.SSPOCon] == 1 ) & ...
            ( [dataStruct.varParList_short.xInclude] == 0) & ...
            ( [dataStruct.varParList_short.yInclude] == 1) & ...
            ( [dataStruct.varParList_short.NLDshift] == 0.5) & ...
            ( [dataStruct.varParList_short.NLDsharpness] == 10);
bin_SSPOCoff = ( [dataStruct.varParList_short.STAwidth] == 3) & ...
            ( [dataStruct.varParList_short.STAshift] == -10) & ...
            ( [dataStruct.varParList_short.SSPOCon] == 0 ) & ...
            ( [dataStruct.varParList_short.xInclude] == 0) & ...
            ( [dataStruct.varParList_short.yInclude] == 1) & ...
            ( [dataStruct.varParList_short.NLDshift] == 0.5) & ...
            ( [dataStruct.varParList_short.NLDsharpness] == 10);
        
ind_SSPOCon = find(bin_SSPOCon);
ind_SSPOCoff = find(bin_SSPOCoff);
    figure();
        plot(bin_SSPOCon,'-o')
        hold on;
        plot(bin_SSPOCoff,'-o')